/* Auto-generated by AADA. Edit freely — AADA will not overwrite this file. */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { chromium } from '@playwright/test';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Credentials come from the ENVIRONMENT ONLY. The AADA runner (/run-tests)
// resolves them from the web viewer's encrypted credential store (Apps →
// <code> → Configuration → Test Credentials) and injects {ENV}_{ROLE}_USERNAME / _PASSWORD into
// this process — there is no local .env.test file. Running Playwright by
// hand? Export the same variables in your shell first.
const env: Record<string, string> = process.env as Record<string, string>;

export const TEST_ENV = (env['TEST_ENV'] ?? 'dev').toUpperCase();
export const BASE_URL: string = env[`${TEST_ENV}_BASE_URL`] ?? 'https://TODO.appiancloud.com';

/**
 * Return credentials for the given role from the environment.
 * Role key is normalised to UPPER_SNAKE: 'tsk_administrators' → 'TSK_ADMINISTRATORS'.
 * Throws a descriptive error if credentials are missing so tests fail fast.
 *
 * Only called lazily by ensureAuth() — a role's credentials are required
 * only when a spec actually declares that role via test.use({ role }).
 */
export function getCredentials(role: string): { username: string; password: string } {
  const key = role.toUpperCase().replace(/-/g, '_');
  const username = env[`${TEST_ENV}_${key}_USERNAME`];
  const password = env[`${TEST_ENV}_${key}_PASSWORD`];
  if (!username || !password) {
    throw new Error(
      `Missing credentials for role "${role}" (${TEST_ENV}_${key}_USERNAME / _PASSWORD not in the environment). ` +
      `Set them in the AADA web viewer (Apps → Configuration → Test Credentials) and run via /run-tests, ` +
      `or export the variables manually for a hand run.`,
    );
  }
  return { username, password };
}

/** Path to the cached Playwright storageState JSON for a role. */
export function authFile(role: string): string {
  return path.join(__dirname, `.auth/${role}.json`);
}

/** Cached sessions older than this are considered stale and re-logged-in. */
const AUTH_TTL_MS = 8 * 60 * 60 * 1000; // 8 hours

// Per-process memoization so parallel tests in one worker share a login.
const _authPromises = new Map<string, Promise<string>>();

/**
 * Ensure a storageState file exists for the given role, logging in via a
 * throwaway browser only when the cached session is missing or stale.
 * Returns the path to the storageState JSON.
 * Roles discovered from the app's knowledge graph:
 *   - 'uam_active_user' (UAM Active User)
 *   - 'uam_administrators' (UAM Administrators)
 *   - 'uam_application_user' (UAM Application User)
 *   - 'uam_process_model_alert_receivers' (UAM Process Model Alert Receivers)
 *   - 'uam_system_admins' (UAM System Admins)
 *   - 'uam_users' (UAM Users)
 *   - 'uam_managers' (UAM managers)
 *
 * A role only needs credentials (web viewer → Apps → Configuration → Test
 * Credentials) if a spec actually uses it via test.use({ role }).
 */
export function ensureAuth(role: string): Promise<string> {
  let promise = _authPromises.get(role);
  if (!promise) {
    promise = doEnsureAuth(role);
    _authPromises.set(role, promise);
  }
  return promise;
}

async function doEnsureAuth(role: string): Promise<string> {
  const file = authFile(role);
  if (fs.existsSync(file) && Date.now() - fs.statSync(file).mtimeMs < AUTH_TTL_MS) {
    return file;
  }
  const { username, password } = getCredentials(role);
  fs.mkdirSync(path.dirname(file), { recursive: true });

  const browser = await chromium.launch();
  try {
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto(`${BASE_URL}/suite/login`);
    await page.locator('#un').fill(username);
    await page.locator('#pw').fill(password);
    await page.locator('#jsLoginButton').click();
    await page.waitForURL(`${BASE_URL}/suite/**`, { timeout: 20_000 });
    await context.storageState({ path: file });
  } finally {
    await browser.close();
  }
  return file;
}
