/* Auto-generated by AADA, then patched: fresh login + verify + trailing-slash-safe URL. */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { chromium } from '@playwright/test';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const env: Record<string, string> = process.env as Record<string, string>;

export const TEST_ENV = (env['TEST_ENV'] ?? 'dev').toUpperCase();
// Strip any trailing slash so `${BASE}/suite/login` never becomes `//suite/login`
// (a double slash redirects to the site root landing page, which has no #un field).
export const BASE_URL: string = (env[`${TEST_ENV}_BASE_URL`] ?? 'https://TODO.appiancloud.com').replace(/\/+$/, '');

export function getCredentials(role: string): { username: string; password: string } {
  const key = role.toUpperCase().replace(/-/g, '_');
  const username = env[`${TEST_ENV}_${key}_USERNAME`];
  const password = env[`${TEST_ENV}_${key}_PASSWORD`];
  if (!username || !password) {
    throw new Error(
      `Missing credentials for role "${role}" (${TEST_ENV}_${key}_USERNAME / _PASSWORD not in the environment). ` +
      `Set them in the AADA web viewer (Apps → Configuration → Test Credentials) and run via /run-tests.`,
    );
  }
  return { username, password };
}

export function authFile(role: string): string {
  return path.join(__dirname, `.auth/${role}.json`);
}

const _authPromises = new Map<string, Promise<string>>();

export function ensureAuth(role: string): Promise<string> {
  let promise = _authPromises.get(role);
  if (!promise) {
    promise = doEnsureAuth(role);
    _authPromises.set(role, promise);
  }
  return promise;
}

async function doEnsureAuth(role: string): Promise<string> {
  const file = authFile(role);
  // Caching intentionally DISABLED: always log in fresh so credential changes
  // take effect and a previously cached (possibly failed) session is never reused.
  const { username, password } = getCredentials(role);
  fs.mkdirSync(path.dirname(file), { recursive: true });

  const browser = await chromium.launch();
  try {
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto(`${BASE_URL}/suite/login`, { waitUntil: 'domcontentloaded' });
    await page.locator('#un').waitFor({ state: 'visible', timeout: 20000 });
    await page.locator('#un').fill(username);
    await page.locator('#pw').fill(password);
    await page.locator('#jsLoginButton').click();
    // Verify login ACTUALLY succeeded: Appian must leave the login/auth page.
    try {
      await page.waitForURL(
        (url) => !/\/suite\/(login|auth)/.test(url.pathname),
        { timeout: 25000 },
      );
    } catch {
      throw new Error(
        `Login FAILED for role "${role}" (user "${username}"): Appian never left the login page ` +
        `within 25s — the credentials were rejected. Verify this account signs in manually at ` +
        `${BASE_URL}/suite/login, then fix the password in the web viewer.`,
      );
    }
    await context.storageState({ path: file });
  } finally {
    await browser.close();
  }
  return file;
}
