/* Auto-generated by AADA. Edit freely — AADA will not overwrite this file. */
import { test as base } from '@playwright/test';
import { ensureAuth } from './auth';

export interface AuthOptions {
  /** Role to run as. Logged in lazily on first use; cached in .auth/. */
  role: string;
}

/**
 * Extended Playwright test with role-based authentication.
 *
 * Tests run as the 'default' role unless they opt into another one:
 *
 *   import { test, expect } from './fixtures';
 *   test.use({ role: 'tsk_administrators' });   // whole file
 *
 *   test.describe('admin flows', () => {
 *     test.use({ role: 'tsk_administrators' }); // one describe block
 *     ...
 *   });
 *
 * Roles discovered from the app's knowledge graph:
 *   - 'uam_active_user' (UAM Active User)
 *   - 'uam_administrators' (UAM Administrators)
 *   - 'uam_application_user' (UAM Application User)
 *   - 'uam_process_model_alert_receivers' (UAM Process Model Alert Receivers)
 *   - 'uam_system_admins' (UAM System Admins)
 *   - 'uam_users' (UAM Users)
 *   - 'uam_managers' (UAM managers)
 *
 * A role only needs credentials (web viewer → Apps → Configuration → Test
 * Credentials) if a spec actually uses it via test.use({ role }).
 */
export const test = base.extend<AuthOptions>({
  role: ['default', { option: true }],
  // Override Playwright's built-in storageState: resolved from the role,
  // logging in on demand (only roles that tests actually use are logged in).
  storageState: async ({ role }, use) => {
    await use(await ensureAuth(role));
  },
});

export { expect } from '@playwright/test';
