// Auto-generated by AADA /generate-fixture — do not edit manually.
// Regenerate with: /generate-fixture <APP_CODE>
import * as fs from 'node:fs';
import * as path from 'node:path';
import { parse as parseYaml } from 'yaml';

interface FixtureFieldDef {
  source: 'ref_data' | 'values';
  table?: string;
  column?: string;
  values?: string[];
}

interface FixtureSpec {
  version: string;
  app: string;
  fixtures: Record<string, { fields: Record<string, FixtureFieldDef> }>;
}

// ── Runtime resolution ────────────────────────────────────────────────

const FIXTURE_NAME = process.env.FIXTURE_NAME ?? 'default';

// Resolve paths relative to this file's location (test/playwright/)
const fixturesDir = path.resolve(__dirname, '..', 'fixtures');
const fixturePath = path.join(fixturesDir, `${FIXTURE_NAME}.fixture.yml`);

let _spec: FixtureSpec | null = null;

function loadSpec(): FixtureSpec | null {
  if (_spec !== null) return _spec;
  try {
    const raw = fs.readFileSync(fixturePath, 'utf-8');
    _spec = parseYaml(raw) as FixtureSpec;
    return _spec;
  } catch {
    // Fixture file absent or unreadable — return null so callers degrade gracefully.
    return null;
  }
}

const _refDataCache = new Map<string, Record<string, string | number | null>[]>();

function loadRefData(table: string): Record<string, string | number | null>[] {
  if (_refDataCache.has(table)) return _refDataCache.get(table)!;
  try {
    const p = path.join(fixturesDir, 'ref-data', `${table}.json`);
    const rows = JSON.parse(fs.readFileSync(p, 'utf-8')) as Record<string, string | number | null>[];
    _refDataCache.set(table, rows);
    return rows;
  } catch {
    return [];
  }
}

function resolveValues(def: FixtureFieldDef): string[] {
  if (def.source === 'ref_data' && def.table) {
    const col = def.column ?? 'name';
    const rows = loadRefData(def.table);
    return rows
      .map((r) => r[col])
      .filter((v): v is string => typeof v === 'string' && v.length > 0);
  }
  if (def.source === 'values' && Array.isArray(def.values)) {
    return def.values.filter((v): v is string => typeof v === 'string');
  }
  return [];
}

// ── Public API ────────────────────────────────────────────────────────

export function createFixtureLoader(interfaceName: string): {
  getFirst(fieldLabel: string): string;
  getValues(fieldLabel: string): string[];
  getRandom(fieldLabel: string): string;
} {
  function getDef(fieldLabel: string): FixtureFieldDef | null {
    const spec = loadSpec();
    if (!spec) return null;
    return spec.fixtures?.[interfaceName]?.fields?.[fieldLabel] ?? null;
  }

  return {
    getFirst(fieldLabel: string): string {
      const def = getDef(fieldLabel);
      if (!def) return '';
      const vals = resolveValues(def);
      return vals[0] ?? '';
    },

    getValues(fieldLabel: string): string[] {
      const def = getDef(fieldLabel);
      if (!def) return [];
      return resolveValues(def);
    },

    getRandom(fieldLabel: string): string {
      const def = getDef(fieldLabel);
      if (!def) return '';
      const vals = resolveValues(def);
      if (vals.length === 0) return '';
      return vals[Math.floor(Math.random() * vals.length)];
    },
  };
}
