/* AADA-HELPERS-VERSION: 8 — AADA-HELPERS-INTEGRITY: 1c1828408f2c3eab
 * AADA-managed file. Do NOT edit this header. If left unedited, AADA
 * auto-upgrades this file on recompile; hand-edits below disable that. */
/* Auto-generated by AADA `generate_tests`. Edit SITE_URL if needed. */
import { type Page, type Locator, expect } from '@playwright/test';

// Path portion only — Playwright's baseURL (set in playwright.config.ts from the
// {TEST_ENV}_BASE_URL env var /run-tests injects) is prepended automatically
// when page.goto() receives a relative URL.
export const SITE_URL = '/suite/sites/user-access-management-anand';

// ── Common Selectors (Appian 25.4 CSS class patterns) ───────────────

export const appian = {
  // Layout
  contentLayout: '[class*="ContentLayout---content_layout"]',
  dialog: '[class*="ModalDialogLayout---modal_dialog"]',
  backdrop: '[class*="ModalDialogManager---modal_backdrop"]',
  fieldLayout: '[class*="FieldLayout---field_layout"]',
  fieldLabel: '[class*="FieldLayout---field_label"]',
  sectionLayout: '[class*="SectionLayout---section_layout"]',

  // Inputs
  textInput: '[class*="TextInput---text"]',
  paragraph: 'textarea',
  datePicker: '[class*="DatePickerWidget---text"]',
  dropdown: '[class*="DropdownWidget---dropdown_value"][role="combobox"]',
  multiDropdown: '[class*="MultipleDropdownWidget---multi_dropdown"]',
  picker: '[class*="PickerWidget---picker"] input',
  pickerChip: '[class*="PickerTokenWidget---chip"]',

  // Buttons
  primaryButton: 'button[class*="Button---btn"][class*="Button---solid"][class*="Button---accent"]',
  secondaryButton: 'button[class*="Button---btn"][class*="Button---outline"]',
  submitButton: (label: string) => `button[class*="Button---btn"]:has-text("${label}")`,
  dialogButton: (label: string) => `button[class*="Button---inModalDialogLayout"]:has-text("${label}")`,

  // Grid
  gridTable: 'table',
  gridRow: 'table tbody tr',
  gridRowSelectable: 'tr[class*="PagingGridLayout---selectable"]',
  gridHeader: '[class*="GridHeaderCell"]',
  gridFooter: '[class*="GridFooter"]',
  sortableHeader: '[aria-sort]',

  // Cards & Tags
  card: '[class*="CardLayout---card_item"]',
  tag: '[class*="TagItem---tag"]',
  progressBar: '[class*="ProgressBarWidget"]',

  // Alerts & Errors
  alert: '[role="alert"]',
  validationError: '[class*="FieldLayout---field_layout"] [role="alert"]',

  // Navigation
  siteNav: 'nav[class*="SiteNav"]',
  siteNavItem: 'a[class*="SiteNavItem"]',
};

// ── Helper Functions ────────────────────────────────────────────────

export function fieldByLabel(page: Page, label: string) {
  return page.locator(appian.fieldLayout).filter({
    has: page.locator(appian.fieldLabel, { hasText: label }),
  }).first();
}

export async function waitForAppianLoad(page: Page) {
  await page.waitForSelector(appian.contentLayout, { timeout: 30000 });
  await page.waitForFunction(() => {
    return document.querySelectorAll('[class*="Spinner"]').length === 0;
  }, { timeout: 10000 }).catch(() => {});
}

export async function waitForDialog(page: Page) {
  await page.waitForSelector(appian.dialog, { timeout: 10000 });
}

export async function waitForDialogClose(page: Page) {
  await expect(page.locator(appian.dialog)).toBeHidden({ timeout: 10000 });
}

/**
 * Commit any in-progress field edit and let Appian's reactive re-render settle.
 *
 * Appian fields with a `saveInto` fire their save on blur, which triggers a
 * server re-evaluation that RE-RENDERS the form. A click (or another fill)
 * that lands while that re-render is in flight gets discarded — the form sits
 * there untouched. Blurring the active element commits the pending save, then
 * we wait for that round-trip to finish (network idle) and drain any client
 * re-render spinner, so the form is stable before the next interaction.
 *
 * Best-effort throughout: on a non-reactive form the blur is a no-op and both
 * waits return immediately.
 */
export async function commitAndSettle(page: Page) {
  await page.evaluate(() => {
    const el = document.activeElement as HTMLElement | null;
    if (el && typeof el.blur === 'function') el.blur();
  }).catch(() => {});
  // Give the blur's saveInto POST a beat to actually dispatch BEFORE waiting
  // for the network to idle — without it, networkidle can observe "idle" in
  // the instant before the request fires and return too early, so the next
  // click lands mid-re-render and Appian swallows it. Then wait for the
  // round-trip to finish (networkidle) and drain any client re-render spinner.
  // All best-effort.
  await page.waitForTimeout(250);
  await page.waitForLoadState('networkidle', { timeout: 6000 }).catch(() => {});
  await page.waitForFunction(
    () => document.querySelectorAll('[class*="Spinner"]').length === 0,
    { timeout: 6000 },
  ).catch(() => {});
}

/**
 * Wait for a submit / record action to resolve. Two real outcomes:
 *
 *   1. AUTO-CLOSE — the form / related-action dialog closes itself once the
 *      submit registers. This is what a HEADED browser does (Approve -> the
 *      dialog disappears).
 *   2. COMPLETED-BUT-OPEN — in a HEADLESS run (how the suite executes in CI),
 *      a related-action dialog (class `ModalDialogLayout---related_action`)
 *      submits the action successfully but does NOT auto-close: it shows a
 *      transient "Action completed" confirmation and waits for the modal's
 *      Close (X) button. The action HAS happened (e.g. the request is
 *      approved) — we just dismiss the leftover confirmation.
 *
 * The confirmation is transient, so we poll every 200ms rather than wait then
 * check once. (Commit fields with `commitAndSettle` before the submit click so
 * it isn't swallowed by an in-flight saveInto re-render.)
 */
export async function waitForActionComplete(page: Page) {
  const dialog = page.locator(appian.dialog).first();
  const completed = page.getByText(/action completed|completed successfully|success/i).first();
  const deadline = Date.now() + 8000;
  while (Date.now() < deadline) {
    if (!(await dialog.isVisible().catch(() => false))) {
      await waitForAppianLoad(page);
      return;
    }
    if (await completed.isVisible().catch(() => false)) {
      const closeBtn = dialog.getByRole('button', { name: /close/i }).first();
      if (await closeBtn.isVisible().catch(() => false)) await closeBtn.click({ force: true }).catch(() => {});
      await dialog.waitFor({ state: 'hidden', timeout: 6000 }).catch(() => {});
      await waitForAppianLoad(page);
      return;
    }
    await page.waitForTimeout(200);
  }
  // Clear failure if the dialog never resolved — the submit never registered,
  // or client-side validation rejected it.
  await expect(
    dialog,
    'submit did not resolve the dialog — validation may have rejected it, or the click did not register',
  ).toBeHidden({ timeout: 8000 });
  await waitForAppianLoad(page);
}

/**
 * Assert no ERROR alert is shown. Appian renders "Action completed" / success
 * confirmations and empty-grid notices ("No items available") as
 * `role="alert"` too, so those are excluded — only genuine error banners
 * trip this check.
 */
export async function expectNoErrorAlert(page: Page) {
  const errors = page.locator('[role="alert"]').filter({ hasNotText: /completed|success|no items/i });
  await expect(errors).toHaveCount(0, { timeout: 5000 });
}

export async function waitForGrid(page: Page) {
  await page.waitForSelector(`${appian.gridTable} tbody tr`, { timeout: 10000 });
}

export async function getGridRowCount(page: Page): Promise<number> {
  return await page.locator(appian.gridRow).count();
}

/**
 * Declaratively sort a grid by a column header. `grid` is either a Locator
 * for the grid's table or a zero-based index into the page's grids. No-op
 * when the header's aria-sort already matches the requested order; otherwise
 * clicks the header until it does (up to twice — Appian cycles
 * none → ascending → descending). Fails if the column never reaches the
 * requested order (e.g. the column is not sortable).
 */
export async function sortGridByColumn(
  page: Page,
  grid: Locator | number,
  column: string,
  order: 'ascending' | 'descending' = 'ascending',
) {
  const gridLoc = typeof grid === 'number' ? page.locator(appian.gridTable).nth(grid) : grid;
  // Match on th (not th[aria-sort]) — an unsorted Appian column may omit the
  // attribute entirely rather than carry aria-sort="none".
  const header = gridLoc.locator('th').filter({ hasText: column }).first();
  await header.scrollIntoViewIfNeeded();
  for (let i = 0; i < 3; i++) {
    const current = await header.getAttribute('aria-sort');
    if (current === order) return;
    const link = header.locator('a').first();
    await ((await link.count()) > 0 ? link : header).click();
    await waitForAppianLoad(page);
    // The sort applies via an async grid re-render. Wait for aria-sort to
    // move off its pre-click value before deciding whether another click is
    // needed — clicking again mid-refresh gets swallowed and the grid ends
    // up one sort state short (e.g. ascending when descending was asked).
    await expect
      .poll(async () => header.getAttribute('aria-sort'), { timeout: 10000 })
      .not.toBe(current);
  }
  await expect(header).toHaveAttribute('aria-sort', order, { timeout: 5000 });
}

/**
 * Type a query into an Appian grid's search box and apply it. `gridIndex` is
 * the zero-based index of the search box when the page has more than one
 * searchable grid (defaults to the first). Appian renders the box as
 * input[placeholder*="Search"] (e.g. "Search DRA Requests"). Waits for the
 * grid to re-query before returning so a following row assertion sees the
 * filtered result set.
 */
export async function searchGrid(page: Page, query: string, gridIndex: number = 0) {
  const input = page.locator('input[placeholder*="Search" i]').nth(gridIndex);
  await input.waitFor({ state: 'visible', timeout: 10000 });
  await input.fill(query);
  await input.press('Enter');
  await waitForAppianLoad(page);
}

/**
 * Assert that some row of a grid contains every one of `cellTexts`. `grid`
 * is either a Locator for the grid's table or a zero-based index into the
 * page's grids. Only rows on the grid's current page are considered — when
 * the target row may be beyond page one (e.g. a newly created record), sort
 * the grid first so it surfaces (sortGridByColumn descending on an ID or
 * created-date column).
 */
export async function expectGridRowMatching(
  page: Page,
  grid: Locator | number,
  cellTexts: string[],
) {
  const gridLoc = typeof grid === 'number' ? page.locator(appian.gridTable).nth(grid) : grid;
  let rows = gridLoc.locator('tbody tr');
  for (const text of cellTexts) {
    rows = rows.filter({ hasText: text });
  }
  await expect(rows.first()).toBeVisible({ timeout: 15000 });
}

/**
 * Search a grid and click the matching row.
 */
export async function searchAndClickRow(page: Page, rowText: string) {
  const searchInput = page.locator('input[placeholder*="Search"], input[placeholder*="search"]').first();
  if (await searchInput.isVisible({ timeout: 3000 }).catch(() => false)) {
    await searchInput.fill(rowText.substring(0, 20));
    await page.keyboard.press('Enter');
    await page.waitForTimeout(1500);
  }
  await page.getByText(rowText, { exact: true }).first().click();
}

/**
 * Locate a single text-like input by its field label, resilient to two Appian
 * layouts that break the naive "FieldLayout with this label → its .text input":
 *
 *   1. SIDE-BY-SIDE fields (e.g. First Name / Last Name in one SectionLayout)
 *      whose labels live in a shared header rather than per-input FieldLayouts —
 *      fieldByLabel then matches BOTH inputs and .fill() throws a strict-mode
 *      violation. getByRole('textbox', { name, exact }) targets the one input
 *      whose ACCESSIBLE NAME is exactly this label.
 *   2. PLACEHOLDER-AS-LABEL fields where the visible field label is a section
 *      heading ("Identify the following information:") and the real per-input
 *      cue is the placeholder — fieldByLabel finds nothing. Appian gives such an
 *      input its accessible name from the placeholder, so step 1 usually catches
 *      it when the plan names the field by its placeholder text; we keep an
 *      explicit placeholder=EXACT match as a backstop.
 *
 * Cascade, most specific → most forgiving. Every tier that could match more
 * than one input demands EXACTLY ONE before returning it — an ambiguous tier is
 * SKIPPED, never silently .first()'d, because filling the adjacent box (the old
 * .first() behaviour) is a wrong-data pass, worse than a clean failure. Only the
 * final unambiguous-failure path returns .first(), so the caller gets a real
 * locator and a clear strict-mode error naming the ambiguity. `selector` scopes
 * to the right input flavour (text vs textarea).
 */
async function resolveInputByLabel(page: Page, label: string, selector: string): Promise<Locator> {
  // The candidate tiers, most specific → most forgiving. Each that could match
  // more than one input demands EXACTLY ONE before being chosen — an ambiguous
  // tier is SKIPPED, never silently .first()'d, because filling the adjacent box
  // is a wrong-data pass, worse than a clean failure.
  //
  //   1. Accessible-name-exact — robust for side-by-side inputs and for inputs
  //      whose placeholder supplies the accessible name.
  //   2. Placeholder (native OR aria) — getByPlaceholder matches both. This is
  //      the reliable hook for Appian paragraph fields whose visible cue is the
  //      placeholder while the FieldLayout label collapses to a useless generic
  //      "Paragraph" (aria-label/labelledby/name all null). Tried BEFORE the
  //      FieldLayout tier precisely because that label is unusable here.
  //   3. The classic FieldLayout-scoped input — the fallback for normally
  //      labelled fields.
  const byRole = page.getByRole('textbox', { name: label, exact: true });
  const byPlaceholder = page.locator(selector).and(page.getByPlaceholder(label, { exact: true }));
  const byLayout = fieldByLabel(page, label).locator(selector);

  // Fix a mid-transition RACE: right after a wizard NEXT, the destination
  // page's inputs aren't in the DOM yet, so instantaneous .count() checks all
  // read 0 and we'd fall through to the never-matching FieldLayout fallback,
  // whose .fill() then waits out the whole test timeout on a dead locator.
  // Auto-wait for ANY tier's first match to become visible before deciding —
  // bounded, best-effort, so a genuinely-absent field still fails fast-ish with
  // a clear error rather than hanging for the full test budget.
  await Promise.race([
    byRole.first().waitFor({ state: 'visible', timeout: 15000 }),
    byPlaceholder.first().waitFor({ state: 'visible', timeout: 15000 }),
    byLayout.first().waitFor({ state: 'visible', timeout: 15000 }),
  ]).catch(() => {});

  if ((await byRole.count()) === 1) return byRole;
  if ((await byPlaceholder.count()) === 1) return byPlaceholder;
  if ((await byLayout.count()) === 1) return byLayout;
  // Nothing matched UNAMBIGUOUSLY. Return the FieldLayout locator (which may be
  // empty or multi-match) so the caller's .fill() raises a clear "no element" /
  // strict-mode error that names the label — never a silent wrong-box fill.
  return byLayout.first();
}

export async function fillTextField(page: Page, label: string, value: string) {
  await (await resolveInputByLabel(page, label, appian.textInput)).fill(value);
}

export async function fillParagraphField(page: Page, label: string, value: string) {
  await (await resolveInputByLabel(page, label, appian.paragraph)).fill(value);
  // Commit the value (blur + settle) so a submit click immediately after isn't
  // swallowed by the field's saveInto re-render.
  await commitAndSettle(page);
}

export async function fillDateField(page: Page, label: string, value: string) {
  // Side-by-side date fields ("From this date" / "To this date") share the
  // ambiguity fillTextField solves — resolve the specific datePicker input by
  // accessible name first, falling back to the FieldLayout-scoped input.
  const byRole = page.getByRole('textbox', { name: label, exact: true });
  const input = (await byRole.count()) === 1
    ? byRole
    : fieldByLabel(page, label).locator(appian.datePicker);
  await input.fill(value);
}

/**
 * Fill an Appian dateTime field — a date input plus a separate time dropdown.
 * The time component is required, so an empty time blocks wizard navigation.
 * value may be "MM/DD/YYYY" (time defaults to 12:00 PM) or
 * "MM/DD/YYYY h:mm AM/PM". The time must match a 30-minute dropdown slot.
 */
export async function fillDateTimeField(page: Page, label: string, value: string) {
  const [datePart, ...timeParts] = value.trim().split(/s+/);
  const time = timeParts.join(" ") || "12:00 PM";
  const field = fieldByLabel(page, label);
  await field.locator(appian.datePicker).fill(datePart);
  await field.locator('[class*="TimeWidget"]').first().click();
  await page.getByRole("option", { name: time, exact: true }).first().click();
}

/**
 * Fill an Appian picker (record/user/group) by typing into its search input
 * and selecting the first suggestion matching the value (or the first
 * suggestion when no text match is found).
 */
export async function fillPickerField(page: Page, label: string, value: string) {
  // pressSequentially (not fill) — Appian's typeahead search only fires on
  // real keystrokes, so a programmatic fill never produces suggestions.
  const field = fieldByLabel(page, label);
  const input = field.locator(appian.picker);
  await input.click();
  await input.pressSequentially(value, { delay: 60 });

  // Wait for OUR suggestion — the option whose text contains the typed value.
  // Matching on the value (rather than the first option) avoids racing a
  // stale dropdown left open by a previous picker, whose options would never
  // contain this value.
  const match = page.locator('[role="option"]').filter({ hasText: value }).first();
  await match.waitFor({ timeout: 10_000 });
  await match.click();

  // Confirm the selection stuck: a token chip appears and the dropdown closes.
  // Without this the next field's interaction can race with a still-open
  // dropdown (selection silently lost, or the overlay blocks the next click).
  await field.locator(appian.pickerChip).first().waitFor({ timeout: 10_000 });
}

/**
 * Upload a local file into an Appian file upload field and wait for the upload
 * to finish. The field is required for form submission, so we block on the
 * uploaded-file chip (a "Remove file" control + size) appearing — clicking
 * Next/Submit before then leaves the field empty.
 *
 * Resolving the <input type="file"> is the tricky part. Appian's
 * MultipleFileUploadWidget renders the real <input> HIDDEN (accessibilityhidden
 * — normal; setInputFiles works on hidden inputs, no visibility wait needed),
 * and inside an editable GRID the FieldLayout label is the GRID's label
 * ("Supporting Documents"), not the per-row field name the plan passes
 * ("Document"). So fieldByLabel(label) → input often matches nothing, and
 * setInputFiles on an empty locator auto-waits the ENTIRE test budget. Cascade:
 *
 *   0. opts.rowIndex — an editable GRID of upload rows (each "Add Document" adds
 *      a row with its own file input) is the one case with MULTIPLE identical
 *      inputs; the rows carry no distinguishing text, so a caller targeting a
 *      specific row passes its zero-based index. Chosen first when given.
 *   1. FieldLayout-scoped by the passed label — a plainly-labelled upload field.
 *   2. Grid-ROW-scoped by label text — when a row's cell text is the label.
 *   3. The lone file input in scope — the common single-upload case, where the
 *      grid label differs from the field name.
 * When none of the above resolves to exactly one input AND several exist, we
 * THROW rather than .first() — silently uploading to row 0 of a multi-row grid
 * (leaving the intended rows empty) is a wrong-data pass. The error tells the
 * caller to pass rowIndex.
 */
export async function uploadFile(
  page: Page,
  label: string,
  filePath: string,
  opts: { rowIndex?: number } = {},
) {
  const scope = (await page.locator('[role="dialog"]').count())
    ? page.locator('[role="dialog"]').first()
    : page;

  const anyInput = scope.locator('input[type="file"]');

  let input: Locator;
  if (typeof opts.rowIndex === "number") {
    // 0. Explicit grid row → that row's file input.
    input = scope.locator(appian.gridRow).nth(opts.rowIndex).locator('input[type="file"]').first();
  } else {
    // 1. FieldLayout-scoped by label.
    const byField = fieldByLabel(page, label).locator('input[type="file"]');
    // 2. Grid-row-scoped: the row whose cell text is the label, its file input.
    const byRow = scope.locator(appian.gridRow).filter({ hasText: label }).locator('input[type="file"]');

    if ((await byField.count()) === 1) input = byField;
    else if ((await byRow.count()) === 1) input = byRow;
    else {
      const n = await anyInput.count();
      if (n === 1) {
        input = anyInput.first(); // unambiguous single upload widget
      } else {
        throw new Error(
          `uploadFile: could not uniquely resolve the file input for "${label}" — ` +
            `found ${n} file input(s) in scope. If this field is one row of an editable ` +
            `upload grid (multiple "Add Document" rows), pass { rowIndex } to target a ` +
            `specific row; row 0 would otherwise be picked silently, leaving the others empty.`,
        );
      }
    }
  }

  await input.setInputFiles(filePath);

  // Confirm the upload registered: the "Remove file" control / size chip appears.
  // Scoped to the dialog so a chip elsewhere can't false-positive. Best-effort —
  // the .catch keeps a non-matching chip from re-introducing the full-budget hang.
  await scope
    .getByText(/Remove file|\d+(\.\d+)?\s*(KB|MB|GB|bytes)/i)
    .first()
    .waitFor({ timeout: 30_000 })
    .catch(() => {});
}

/**
 * Check or uncheck an Appian boolean checkbox by its FIELD label.
 *
 * The label passed in is the FIELD label — a field_label div (e.g.
 * "Certification") — NOT the checkbox's own <label>, which is the long CHOICE
 * sentence ("I certify that the information provided is accurate…"). So we match
 * the FieldLayout container by its field_label (via fieldByLabel), then find the
 * checkbox inside it by role. Matching a <label> named after the field label
 * finds nothing (the field-label-vs-choice-label split we hit with radios).
 *
 * Toggling mirrors selectRadioOption: check({force}) first (bypasses the styled
 * <div> overlay on the real <input>), then fall back to clicking the choice
 * <label> — Appian toggles on the label text, not always the hidden input. Only
 * acts when the current state differs from the desired one.
 */
export async function setCheckboxField(page: Page, label: string, checked: boolean = true) {
  const field = fieldByLabel(page, label);
  const input = field.getByRole('checkbox').first();
  await input.scrollIntoViewIfNeeded().catch(() => {});
  if ((await input.isChecked().catch(() => false)) !== checked) {
    // setChecked (not check) so this also handles unchecking (checked=false).
    await input.setChecked(checked, { force: true }).catch(async () => {
      // Forced set clicked the input but Appian's handler didn't fire — click
      // the visible choice <label>, which is what Appian actually toggles on.
      await field.locator('label').first().click();
    });
    await expect(input).toBeChecked({ checked, timeout: 5_000 });
  }
}

/** Escape a string for literal use inside a RegExp (for exact-text matching). */
function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Resolve a dropdown's combobox trigger by its field label. Cascade, most
 * specific → most forgiving, each tier returning only on an UNAMBIGUOUS (=== 1)
 * match so an ambiguous tier is skipped rather than silently .first()'d:
 *
 *   1. Accessible-name-exact combobox — the robust match, and the one that
 *      disambiguates the side-by-side layout: when two dropdowns (State /
 *      Country) share one FieldLayout container, fieldByLabel(label).locator(
 *      dropdown) matches BOTH and a later click/waitFor throws strict-mode;
 *      getByRole targets the single combobox whose accessible name is this label.
 *   2. FieldLayout-scoped dropdown — the classic ABOVE-label field.
 *   3. Displayed-placeholder-text — a PLACEHOLDER-LABELED dropdown (e.g.
 *      "Service or Component") whose FieldLayout label collapses to a generic
 *      "Dropdown" and whose real cue is the placeholder the UNSELECTED combobox
 *      DISPLAYS as its text. Tiers 1-2 both miss it (accessible name and field
 *      label are "Dropdown"). Matched by exact displayed text — only valid while
 *      unselected, which is exactly when we open it; the sibling placeholders
 *      ("Select a state" / "Select a country") differ, so no collision.
 *
 * Falls back to the FieldLayout locator's first match so a genuinely missing
 * dropdown yields a clear labelled error rather than a silent no-op.
 */
async function resolveDropdownTrigger(page: Page, label: string): Promise<Locator> {
  const byRole = page.getByRole('combobox', { name: label, exact: true });
  const byLayout = fieldByLabel(page, label).locator(appian.dropdown);
  // Exact displayed text (anchored regex), not hasText's substring match, so a
  // longer sibling placeholder can't be picked by accident.
  const byText = page.locator(appian.dropdown)
    .filter({ hasText: new RegExp(`^\\s*${escapeRegExp(label)}\\s*$`) });

  // Same mid-transition RACE guard as resolveInputByLabel: right after a wizard
  // NEXT the destination page's combobox isn't in the DOM yet, so instantaneous
  // counts read 0 and we fall to the empty fallback whose waitFor hangs out the
  // clock. Auto-wait for ANY tier's first match to appear before deciding.
  await Promise.race([
    byRole.first().waitFor({ state: 'visible', timeout: 15000 }),
    byLayout.first().waitFor({ state: 'visible', timeout: 15000 }),
    byText.first().waitFor({ state: 'visible', timeout: 15000 }),
  ]).catch(() => {});

  if ((await byRole.count()) === 1) return byRole;
  if ((await byLayout.count()) === 1) return byLayout;
  if ((await byText.count()) === 1) return byText;
  return byLayout.first();
}

export async function openDropdown(page: Page, label: string) {
  const trigger = await resolveDropdownTrigger(page, label);
  await trigger.waitFor({ state: 'visible', timeout: 10000 });
  // Open once. Do NOT re-click to retry — a second click on an already-open
  // dropdown toggles it shut, and a record-backed menu re-renders its
  // <li role="option"> items as its data query resolves, so toggling churns
  // the list and the later option click keeps hitting a detaching element.
  await trigger.click();
  const options = page.locator('[role="option"]');
  // A search-GATED dropdown (a large option set, ~100+) renders NO options
  // until you type into its search box — so options.first() would never appear
  // and we must not block on it. Detect the search box; when present, return
  // immediately and let selectDropdown drive the typing.
  const search = dropdownSearchBox(page);
  if (await search.count() > 0) return;
  // Wait for options to appear, but BEST-EFFORT — never throw here. Some
  // placeholder-labeled / record-backed dropdowns open as an active combobox
  // whose option list arrives a beat later OR is search-gated without a search
  // box we can pin (e.g. "Service or Component"). If we hard-threw on a 10s
  // no-options wait, selectDropdown's retry would just re-open and re-throw
  // until the outer timeout. Returning lets selectDropdown decide: click the
  // target if it rendered, else type to filter (search box or keyboard).
  await options.first().waitFor({ state: 'visible', timeout: 10000 }).catch(() => {});
  // If options did render, wait for the count to stop changing — the data query
  // has finished populating the menu — so the later click hits a stable element
  // rather than one mid-re-render. If none rendered, fall through immediately.
  let prev = -1;
  for (let i = 0; i < 6; i++) {
    const count = await options.count();
    if (count === 0) return;            // nothing to settle — let selectDropdown filter
    if (count === prev) return;         // count stabilised
    prev = count;
    await page.waitForTimeout(250);
  }
}

/**
 * The search input inside an OPEN dropdown overlay. A long Appian dropdown
 * (e.g. Country) renders a text input at the top of the open menu and shows
 * only the FIRST page of options (~16) until you type to filter — the target
 * value is usually not on that first page. A short one (e.g. State) renders
 * all its options inline with no search box.
 *
 * The open menu's container class varies by widget (DropdownWidget---dropdown
 * for a classic dropdown, MenuWidget---listbox for the record/menu-backed one
 * seen on Country), so we match the input by living inside ANY open listbox or
 * a *Widget---{dropdown,listbox,menu} container, scoped to visible so a closed
 * dropdown's hidden input doesn't match. Broad on container, precise on "a
 * visible text input that just appeared in the open menu".
 */
function dropdownSearchBox(page: Page): Locator {
  return page
    .locator('[role="listbox"], [class*="DropdownWidget---dropdown"], [class*="MenuWidget---listbox"], [class*="Widget---menu"]')
    .locator('input[type="text"], input[role="combobox"], input[role="searchbox"]')
    .locator('visible=true');
}

export async function selectDropdownOption(page: Page, optionText: string) {
  // A record-backed dropdown re-renders its <li role="option"> items each
  // time its data query re-resolves, so a single click can race a detach
  // ("element is not stable / detached from the DOM"). expect.toPass retries
  // the whole click — re-resolving the locator each attempt — until one
  // lands on a stable element, which is the robust pattern for an option
  // list that settles a beat after it first appears.
  await expect(async () => {
    await page.locator('[role="option"]').filter({ hasText: optionText }).first().click({ timeout: 2000 });
  }).toPass({ timeout: 15000 });
}

/**
 * Filter an open, search-gated dropdown to the given value and return the
 * matching option locator once it appears.
 *
 * Strategy — type the FULL value first, broaden only on miss. Each keystroke
 * batch fires a server round-trip (Appian re-queries the option list), so the
 * cheapest path is one query with the most specific prefix: it returns the
 * smallest list (often exactly the target) and settles once. We do NOT type
 * incrementally from short→long — that pays for a round-trip on every broad,
 * useless prefix. Instead we start specific and only SHORTEN the query if the
 * full value over-filters to nothing (a trailing space / case / punctuation
 * mismatch), stopping the instant a match shows. Common case = one round-trip.
 */
async function filterDropdownTo(page: Page, search: Locator, value: string): Promise<Locator> {
  const target = page.locator('[role="option"]').filter({ hasText: value }).first();
  for (const prefix of searchPrefixes(value)) {
    await search.fill('');
    await search.fill(prefix);
    // One settle for this query's round-trip, then check for the exact value.
    try {
      await target.waitFor({ state: 'visible', timeout: 4000 });
      return target;
    } catch {
      // Over-filtered (or still loading a slow query) — broaden and retry.
    }
  }
  // Last resort: wait out a slow final query on the broadest prefix.
  await target.waitFor({ state: 'visible', timeout: 6000 });
  return target;
}

/**
 * Same specific→broad filtering as filterDropdownTo, but driving the OPEN
 * dropdown's search input via the keyboard instead of a located <input>. Appian
 * focuses that input the moment the combobox opens, so keystrokes reach it even
 * when its DOM node doesn't match dropdownSearchBox's container-scoped locator
 * (overlay markup varies across Appian versions). This is the fallback that
 * makes a search-gated list (e.g. Country, ~200 options) work regardless of
 * whether we could pin the input by selector.
 */
async function filterDropdownByKeyboard(page: Page, value: string): Promise<Locator> {
  const target = page.locator('[role="option"]').filter({ hasText: value }).first();
  for (const prefix of searchPrefixes(value)) {
    // Clear whatever a previous prefix typed (select-all + delete works on the
    // focused search input without needing its locator), then type this prefix.
    await page.keyboard.press('ControlOrMeta+A');
    await page.keyboard.press('Delete');
    await page.keyboard.type(prefix, { delay: 20 });
    try {
      await target.waitFor({ state: 'visible', timeout: 4000 });
      return target;
    } catch {
      // Over-filtered (or still loading a slow query) — broaden and retry.
    }
  }
  await target.waitFor({ state: 'visible', timeout: 6000 });
  return target;
}

/**
 * Prefixes to type into a search-gated dropdown, most specific to broadest:
 * the full value first (smallest, usually exact list — one round-trip), then
 * shrinking cuts to recover from a trailing-space/case/punctuation mismatch.
 * De-duped so a short value doesn't retype the same string.
 */
function searchPrefixes(value: string): string[] {
  return Array.from(new Set(
    [value, value.slice(0, 8), value.slice(0, 5), value.slice(0, 3)].filter((p) => p.length > 0),
  ));
}

/**
 * Open a dropdown and select an option in one resilient unit. A record-backed
 * Appian dropdown can re-render and even COLLAPSE its menu a beat after it
 * first opens, so opening and selecting in two independent steps races: the
 * menu may be gone by the time we click the option. expect.toPass retries the
 * whole open+click — reopening the menu each attempt — until a click lands.
 *
 * Handles both dropdown flavours: a small inline list (click the option
 * directly) and a large SEARCH-GATED list (~100+ options, e.g. Country) that
 * renders nothing until you type — for which we type the value into the search
 * box first (see filterDropdownTo). Prefer this over calling openDropdown +
 * selectDropdownOption separately.
 */
export async function selectDropdown(page: Page, label: string, optionText: string) {
  await expect(async () => {
    await openDropdown(page, label);
    const options = page.locator('[role="option"]');
    const target = options.filter({ hasText: optionText }).first();

    // Fast path: the target is already among the rendered options (a short
    // list like State that shows everything inline). Click it and we're done.
    if (await target.count() > 0) {
      await target.click({ timeout: 3000 });
      return;
    }

    // Target not among the currently-shown options. Type to filter/reveal it —
    // a long list only renders its first page (Country: "United States" isn't on
    // it) until you type. Prefer a located search box; else drive the combobox's
    // focused input via the keyboard. Both are bounded (~seconds), NOT the full
    // toPass budget, so a value that never appears fails fast rather than hanging.
    const search = dropdownSearchBox(page);
    try {
      const option = (await search.count() > 0)
        ? await filterDropdownTo(page, search.first(), optionText)
        : await filterDropdownByKeyboard(page, optionText);
      await option.click({ timeout: 3000 });
      return;
    } catch {
      // Filtering didn't surface the value. If the list DID materialise but
      // lacks it, this is almost certainly a real app bug — most commonly a
      // record-backed dropdown missing its data: binding, which renders the
      // field with only a placeholder/stray entry and never populates the real
      // choices. Throw a clear message naming the value and what IS on offer so
      // the failure reads as "option not available" (app bug), not "flaky test".
      if (await options.count() > 0) {
        const available = (await options.allInnerTexts())
          .map((s) => s.trim()).filter(Boolean).join(', ');
        throw new Error(
          `selectDropdown: option "${optionText}" is not in the "${label}" list. ` +
            `The dropdown opened with these options: [${available}]. ` +
            `If the expected choices are missing entirely, the field is likely a record-backed ` +
            `dropdown missing its data: binding (renders but never populates) — an APP bug, not a test bug.`,
        );
      }
      throw new Error(
        `selectDropdown: could not select "${optionText}" in "${label}" — the dropdown opened but ` +
          `no options ever rendered (even after typing to filter).`,
      );
    }
  }).toPass({ timeout: 25000 });
}

/**
 * Select a choice in an Appian radio-button field. Unlike a dropdown, a radio
 * group renders its choices inline — no combobox to open — as
 * <input role="radio"> elements under a <div role="radiogroup"> whose
 * accessible name is the field label. So we scope to the radiogroup by that
 * name and select the option by its accessible name (the visible choice text).
 *
 * Falls back to the FieldLayout container (matched by label text) when the
 * radiogroup's accessible name isn't wired to the label.
 *
 * Selection is a check({ force: true }) THEN a click on the visible choice text
 * on failure — and the .catch() is essential, not defensive polish:
 *   - force:true bypasses the styled <div class="RadioSelect---choice_pair">
 *     that Appian overlays on the real <input type="radio"> (a plain check()
 *     hangs on "<div> intercepts pointer events").
 *   - BUT clicking the underlying <input>, even forced, often does NOT fire
 *     Appian's selection handler — the state never flips, so check() throws its
 *     own post-condition "Clicking the checkbox did not change its state".
 *     Appian toggles on the choice_pair TEXT, not the hidden input, so the
 *     .catch() clicks getByText(optionText) — that is what actually selects it.
 * The direct check() is kept as the cheap first attempt (it works on some radio
 * variants); the text click is the reliable fallback. commitAndSettle after:
 * these radios carry a saveInto that re-renders the form (reveals sections), so
 * a submit/next click immediately after must not race that round-trip.
 */
export async function selectRadioOption(page: Page, label: string, optionText: string) {
  const byRole = page.getByRole('radiogroup', { name: label });
  const group = (await byRole.count()) > 0 ? byRole.first() : fieldByLabel(page, label);
  // exact:true on both the radio-name and the fallback text — radio choices are
  // often short and colliding ("No" vs "No, I am not willing..."), so a
  // substring match would select the wrong choice.
  const option = group.getByRole('radio', { name: optionText, exact: true });
  await option.scrollIntoViewIfNeeded();
  await option.check({ force: true }).catch(async () => {
    // Force-check clicked the input but Appian's handler didn't fire — click
    // the visible choice text, which is what Appian actually listens on.
    await group.getByText(optionText, { exact: true }).first().click();
  });
  await expect(option).toBeChecked({ timeout: 5_000 });
  // These radios reveal/hide sections via saveInto — let that re-render settle.
  await commitAndSettle(page);
}

/**
 * After opening an Appian dropdown, wait for options to fully load then select nth item.
 */
export async function pickDropdownNth(page: Page, nth: number = 1, timeout = 8000) {
  await page.waitForFunction(
    (n: number) => document.querySelectorAll('[role="option"]').length > n,
    nth, { timeout }
  ).catch(() => {});
  await page.locator('[role="option"]').nth(nth).click({ timeout: 5000 });
}

export async function clickButton(page: Page, label: string) {
  // When a dialog is open, scope the search to it — the :has-text selector
  // is a substring match, so an unscoped lookup can resolve to a button on
  // the page behind the dialog (e.g. "Create" matching a "Create Request"
  // quick action) and the click is then intercepted by the dialog overlay.
  const dialog = page.locator('[role="dialog"]');
  const inDialog = (await dialog.count()) > 0;
  const scope = inDialog ? dialog.first() : page;
  // Commit any in-progress field edit before clicking. Appian fields with a
  // saveInto fire on blur and trigger a server re-render; a submit click that
  // lands mid-re-render gets swallowed and the form never submits. Settling
  // first lets that round-trip finish before we click.
  if ((await page.locator('input:focus, textarea:focus').count()) > 0) {
    await commitAndSettle(page);
  }
  // force: true lands the click directly on the button — without it,
  // Playwright re-runs actionability checks that can race an Appian re-render
  // and dispatch the click onto a stale node, which Appian then discards.
  const button = scope.locator(appian.submitButton(label));
  if ((await button.count()) > 0) {
    await button.first().click({ force: true });
    await settleAfterClick(page);
    return;
  }
  // No <button> matched — Appian renders some actions as link-styled controls,
  // notably an editable grid's "Add <row>" (e.g. "Add Document"), which is an
  // <a>, not a <button>. Fall back to a role/name link, then any link, before
  // giving up. This keeps clickButton usable for those add-row affordances
  // without the caller needing a separate helper.
  const linkByRole = scope.getByRole('link', { name: label });
  if ((await linkByRole.count()) > 0) {
    await linkByRole.first().click({ force: true });
    await settleAfterClick(page);
    return;
  }
  const linkByText = scope.locator('a').filter({ hasText: label });
  if ((await linkByText.count()) > 0) {
    await linkByText.first().click({ force: true });
    await settleAfterClick(page);
    return;
  }
  // Nothing matched — click the (empty) button locator so the failure names
  // the missing control clearly rather than silently no-op'ing.
  await button.first().click({ force: true });
}

/**
 * Wait for the server round-trip a button click triggers to land, so the NEXT
 * helper call runs against the settled page — not a mid-transition one.
 *
 * The race this closes: a wizard NEXT/Back (or any submit) POSTs and re-renders
 * the form; without this, clickButton returns the instant the click dispatches,
 * and the next fill/select runs before the destination page's inputs exist,
 * reading them as absent. All waits are best-effort (.catch) because a submit
 * that closes the dialog or navigates makes some of these transiently throw —
 * we never want the settle itself to fail the step.
 */
async function settleAfterClick(page: Page) {
  // Let the POST actually dispatch before we test for idle — networkidle can
  // otherwise observe the pre-request lull and return too early.
  await page.waitForTimeout(250);
  await page.waitForLoadState('networkidle', { timeout: 8000 }).catch(() => {});
  await page.waitForFunction(
    () => document.querySelectorAll('[class*="Spinner"]').length === 0,
    { timeout: 8000 },
  ).catch(() => {});
}

export async function clickAdminTab(page: Page, tabName: string) {
  const tab = page.locator(`[class*="CardLayout---card_item"][class*="CardLayout---linked_card"]`).filter({
    hasText: tabName,
  }).first();
  await tab.click();
  await page.waitForTimeout(1500);
  await waitForAppianLoad(page);
}

export async function clickRecordAction(page: Page, buttonText: string): Promise<boolean> {
  const regex = new RegExp(buttonText, 'i');

  // Primary: standard Appian content button.
  const contentBtn = page.locator(`button[class*="Button---btn"]`).filter({ hasText: regex }).first();
  await contentBtn.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});
  if (await contentBtn.isVisible().catch(() => false)) { await contentBtn.click(); return true; }

  // Fallback 1: any <button> element (record header actions without standard class).
  const anyBtn = page.locator('button').filter({ hasText: regex }).first();
  await anyBtn.waitFor({ state: 'visible', timeout: 3000 }).catch(() => {});
  if (await anyBtn.isVisible().catch(() => false)) { await anyBtn.click(); return true; }

  // Fallback 2: any <a> element (link-styled record actions).
  const linkBtn = page.locator('a').filter({ hasText: regex }).first();
  await linkBtn.waitFor({ state: 'visible', timeout: 3000 }).catch(() => {});
  if (await linkBtn.isVisible().catch(() => false)) { await linkBtn.click(); return true; }

  return false;
}

export async function expectValidationErrors(page: Page) {
  await expect(page.locator(appian.validationError).first()).toBeVisible({ timeout: 5000 });
}

export async function navigateToPage(page: Page, pageSlug: string) {
  await page.goto(`${SITE_URL}/page/${pageSlug}`);
  await waitForAppianLoad(page);
}

// ── Multi-role helpers ──────────────────────────────────────────────

/**
 * Switch to a different role mid-test by performing a real Appian UI login.
 * Credentials come from the process environment — /run-tests resolves them
 * from the web viewer's encrypted Test Credentials store and injects
 * {TEST_ENV}_{ROLE}_USERNAME / _PASSWORD (+ {TEST_ENV}_BASE_URL) before
 * spawning Playwright. Configure them under Apps → Configuration → Test
 * Credentials in the web viewer.
 *
 * Example usage in a multi-role test:
 *
 *   test('full review workflow', async ({ page }) => {
 *     // page starts as default user (storageState from playwright.config.ts)
 *     await loginAsRole(page, 'tsk_administrators');  // switch to admin
 *     // ... admin actions ...
 *     await loginAsRole(page, 'default');             // switch back
 *   });
 *
 * For tests that only ever use one non-default role, prefer
 * test.use({ storageState: AUTH_FILES.role }) at the describe level instead.
 */
export async function loginAsRole(page: Page, role: string): Promise<void> {
  const env = process.env as Record<string, string>;
  const TEST_ENV = (env['TEST_ENV'] ?? 'dev').toUpperCase();
  const BASE_URL = env[`${TEST_ENV}_BASE_URL`] ?? 'https://TODO.appiancloud.com';
  const key = role.toUpperCase().replace(/-/g, '_');
  const username = env[`${TEST_ENV}_${key}_USERNAME`];
  const password = env[`${TEST_ENV}_${key}_PASSWORD`];
  if (!username || !password) {
    throw new Error(
      `loginAsRole: missing credentials for role "${role}" (looked for ${TEST_ENV}_${key}_USERNAME / _PASSWORD). ` +
        `Configure this role for the "${TEST_ENV.toLowerCase()}" environment under ` +
        `Apps → Configuration → Test Credentials in the web viewer, then re-run /run-tests.`,
    );
  }
  await page.goto(`${BASE_URL}/suite/login`);
  await page.locator('#un').fill(username);
  await page.locator('#pw').fill(password);
  await page.locator('#jsLoginButton').click();
  await page.waitForURL(`${BASE_URL}/suite/**`, { timeout: 20_000 });
}
