/* Auto-generated by AADA. Edit freely — AADA will not overwrite this file. */
import { defineConfig, devices } from '@playwright/test';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Environment-driven config: the AADA runner (/run-tests) injects TEST_ENV,
// {ENV}_BASE_URL, and per-role credentials resolved from the web viewer's
// encrypted credential store. No .env.test file is read.
const _env = process.env as Record<string, string>;
const _testEnv = (_env['TEST_ENV'] ?? 'dev').toUpperCase();
const _baseUrl: string = _env[`${_testEnv}_BASE_URL`] ?? 'https://TODO.appiancloud.com';

export default defineConfig({
  testDir: '.',
  // Per-test timeout. The default 30s is tight for Appian flows that chain a
  // navigation, a record-action dialog, a reactive form submit, and a grid
  // re-query — especially when a submit click is retried after a swallowed
  // mid-re-render click. 60s leaves headroom without masking real hangs.
  timeout: 60_000,
  // Default to one worker — parallel headless Chromium instances exhaust
  // memory-constrained containers (tabs die with "Target crashed"). Override
  // via the PW_WORKERS env var or `npx playwright test --workers=N`
  // on a machine with more headroom.
  workers: _env['PW_WORKERS'] ? Number(_env['PW_WORKERS']) : 1,
  outputDir: path.resolve(__dirname, '../../../tmp/test-results/playwright'),
  reporter: [
    ['list'],
    ['json', { outputFile: path.resolve(__dirname, '../../../tmp/test-results/playwright/results.json') }],
    ['html', { outputFolder: path.resolve(__dirname, '../../../tmp/test-results/playwright-html'), open: 'never' }],
  ],
  use: {
    baseURL: _baseUrl,
  },
  projects: [
    // Authentication is handled lazily by the `role` fixture in fixtures.ts —
    // no setup project required.
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        video: 'retain-on-failure',
      },
    },
  ],
});
